# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/koroushemari/monte-carlo-option-pricing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/koroushemari/monte-carlo-option-pricing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/koroushemari/monte-carlo-option-pricing/CMakeFiles /Users/koroushemari/monte-carlo-option-pricing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/koroushemari/monte-carlo-option-pricing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monte_carlo_simulator

# Build rule for target.
monte_carlo_simulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monte_carlo_simulator
.PHONY : monte_carlo_simulator

# fast build rule for target.
monte_carlo_simulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/build
.PHONY : monte_carlo_simulator/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

src/GBMSimulator.o: src/GBMSimulator.cpp.o
.PHONY : src/GBMSimulator.o

# target to build an object file
src/GBMSimulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/GBMSimulator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GBMSimulator.cpp.o
.PHONY : src/GBMSimulator.cpp.o

src/GBMSimulator.i: src/GBMSimulator.cpp.i
.PHONY : src/GBMSimulator.i

# target to preprocess a source file
src/GBMSimulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/GBMSimulator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GBMSimulator.cpp.i
.PHONY : src/GBMSimulator.cpp.i

src/GBMSimulator.s: src/GBMSimulator.cpp.s
.PHONY : src/GBMSimulator.s

# target to generate assembly for a file
src/GBMSimulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/GBMSimulator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GBMSimulator.cpp.s
.PHONY : src/GBMSimulator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monte_carlo_simulator.dir/build.make CMakeFiles/monte_carlo_simulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/GBMSimulator_test.o: tests/GBMSimulator_test.cpp.o
.PHONY : tests/GBMSimulator_test.o

# target to build an object file
tests/GBMSimulator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/GBMSimulator_test.cpp.o
.PHONY : tests/GBMSimulator_test.cpp.o

tests/GBMSimulator_test.i: tests/GBMSimulator_test.cpp.i
.PHONY : tests/GBMSimulator_test.i

# target to preprocess a source file
tests/GBMSimulator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/GBMSimulator_test.cpp.i
.PHONY : tests/GBMSimulator_test.cpp.i

tests/GBMSimulator_test.s: tests/GBMSimulator_test.cpp.s
.PHONY : tests/GBMSimulator_test.s

# target to generate assembly for a file
tests/GBMSimulator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/GBMSimulator_test.cpp.s
.PHONY : tests/GBMSimulator_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... monte_carlo_simulator"
	@echo "... unit_tests"
	@echo "... src/GBMSimulator.o"
	@echo "... src/GBMSimulator.i"
	@echo "... src/GBMSimulator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/GBMSimulator_test.o"
	@echo "... tests/GBMSimulator_test.i"
	@echo "... tests/GBMSimulator_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

